const $ = (s) => document.querySelector(s);
const $$ = (s) => [...document.querySelectorAll(s)];
const fmt = new Intl.NumberFormat();
const state = { corpora: [], selected: null, catalog: null, storage: null, routes: [], providers: [], lastJob: null, lastCorpus: null, ingestJob: null, eventSource: null };

function escapeHtml(s=''){ return String(s).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c])); }
function pct(x){ return `${Math.round((Number(x)||0)*1000)/10}%`; }
function bytes(n=0){ const u=['B','KB','MB','GB','TB']; let i=0,v=Number(n)||0; while(v>=1024&&i<u.length-1){v/=1024;i++;} return `${v.toFixed(i?1:0)} ${u[i]}`; }
function shortId(s=''){ return String(s).length>18?`${String(s).slice(0,8)}…${String(s).slice(-6)}`:String(s); }
function money(x=0){ return `$${Number(x||0).toFixed(Number(x||0)<1?4:2)}`; }
function toast(msg,error=false){ const el=$('#toast'); if(!el)return; el.textContent=msg; el.className='toast show'+(error?' error':''); clearTimeout(toast.t); toast.t=setTimeout(()=>el.className='toast',2600); }
async function api(path,options={}){ const r=await fetch(path,options); let d=null; try{d=await r.json()}catch{d={detail:await r.text()}} if(!r.ok) throw new Error(d.detail||`${r.status} ${r.statusText}`); return d; }
function uploadForm(path,formData,onProgress){return new Promise((resolve,reject)=>{const x=new XMLHttpRequest();x.open('POST',path);x.responseType='json';x.upload.onprogress=e=>{if(e.lengthComputable&&onProgress)onProgress(e.loaded/e.total,e.loaded,e.total)};x.onerror=()=>reject(new Error('Upload connection failed'));x.onload=()=>{const d=x.response||{};if(x.status>=200&&x.status<300)resolve(d);else reject(new Error(d.detail||`${x.status} upload failed`));};x.send(formData);});}

async function checkHealth(){ try{const d=await api('/health'); if($('#healthText'))$('#healthText').textContent=`Runtime ${d.version} online`; }catch(e){ if($('#healthText'))$('#healthText').textContent='Runtime unavailable'; } }

function connectEvents(){
  if(!window.EventSource || state.eventSource) return;
  const es=new EventSource('/api/events'); state.eventSource=es;
  es.addEventListener('ingest',e=>{ try{handleIngestEvent(JSON.parse(e.data));}catch{} });
  es.addEventListener('evaluation',e=>{ try{handleEvaluationEvent(JSON.parse(e.data));}catch{} });
  es.onerror=()=>{};
}
function handleIngestEvent(d){
  if(state.ingestJob && d.job_id===state.ingestJob){ renderIngestProgress(d); if(d.status==='complete'||d.status==='partial'){ loadCorpora().then(()=>selectCorpus(d.corpus_id)); toast(d.status==='complete'?'Corpus ingest complete':'Corpus ingested with unresolved semantic channels',d.status==='partial'); } if(d.status==='failed')toast(d.error||'Ingest failed',true); }
  if(document.body.dataset.page==='admin') scheduleAdminRefresh();
}
function handleEvaluationEvent(d){
  if(state.lastJob && d.job_id===state.lastJob) renderLiveProgress(d);
  if(document.body.dataset.page==='admin') scheduleAdminRefresh();
}
let adminRefreshTimer=null; function scheduleAdminRefresh(){ clearTimeout(adminRefreshTimer); adminRefreshTimer=setTimeout(loadAdmin,350); }

// ---- Workspace ingest -------------------------------------------------------
function initUpload(){
  const input=$('#fileInput'), dz=$('#dropzone'), btn=$('#uploadBtn'); if(!input||!btn)return;
  const render=()=>{const files=[...input.files]; btn.disabled=!files.length; const list=$('#fileList'); list.className='file-list'+(files.length?'':' empty'); list.innerHTML=files.length?files.map(f=>`<span class="file-pill">${escapeHtml(f.name)} · ${bytes(f.size)}</span>`).join(''):'No files selected';};
  input.addEventListener('change',render);
  ['dragenter','dragover'].forEach(x=>dz.addEventListener(x,e=>{e.preventDefault();dz.classList.add('dragging')}));
  ['dragleave','drop'].forEach(x=>dz.addEventListener(x,e=>{e.preventDefault();dz.classList.remove('dragging')}));
  dz.addEventListener('drop',e=>{ input.files=e.dataTransfer.files; render(); });
  btn.addEventListener('click',async()=>{
    const files=[...input.files]; if(!files.length)return;
    const fd=new FormData(); files.forEach(f=>fd.append('files',f)); btn.disabled=true; btn.textContent='Queueing…';
    try{ renderIngestProgress({status:'uploading',progress:0,total_files:files.length,completed_files:0}); const job=await uploadForm('/api/ingest-jobs',fd,(p,loaded,total)=>{renderIngestProgress({status:'uploading',progress:p,total_files:files.length,completed_files:0,path:`${bytes(loaded)} / ${bytes(total)}`})}); state.ingestJob=job.job_id; renderIngestProgress({status:'queued',progress:0,total_files:job.total_files,completed_files:0}); btn.textContent='Queued'; await pollIngestJob(job.job_id); }
    catch(e){toast(e.message,true);btn.disabled=false;btn.textContent='Queue ingest';}
  });
}
function renderIngestProgress(d){
  const box=$('#ingestProgress'); if(!box)return; box.classList.remove('hidden'); const p=Number(d.progress||0); $('#ingestPct').textContent=pct(p); $('#ingestBar').style.width=pct(p); $('#ingestStatus').textContent=d.status||d.phase||'running'; $('#ingestDetail').textContent=d.path?`${d.completed_files||0}/${d.total_files||0} · ${d.path}`:`${d.completed_files||0}/${d.total_files||0} files`;
}
async function pollIngestJob(jobId){
  for(let i=0;i<1200;i++){ const j=await api(`/api/ingest-jobs/${encodeURIComponent(jobId)}`); renderIngestProgress({status:j.status,progress:j.progress,completed_files:j.completed_files,total_files:j.total_files}); if(j.status==='complete'||j.status==='partial'||j.status==='failed'){ const btn=$('#uploadBtn'); if(btn){btn.disabled=false;btn.textContent='Queue ingest';} if(j.status==='complete'||j.status==='partial'){await loadCorpora(); const sel=$('#corpusSelect'); if(sel){sel.value=j.corpus_id; await selectCorpus(j.corpus_id);} } else toast(j.message,true); return;} await new Promise(r=>setTimeout(r,600)); }
}

// ---- Corpus / explorer ------------------------------------------------------
async function loadCorpora(){ const d=await api('/api/corpora'); state.corpora=d.corpora||[]; const sel=$('#corpusSelect'); if(!sel)return; const prev=sel.value; sel.innerHTML='<option value="">Choose a corpus…</option>'+state.corpora.map(c=>`<option value="${escapeHtml(c.corpus_id)}">${shortId(c.corpus_id)} · ${c.assets.length} assets · ${fmt.format(c.required_blocks)} blocks</option>`).join(''); if(state.corpora.some(c=>c.corpus_id===prev))sel.value=prev; }
async function selectCorpus(id){ state.selected=state.corpora.find(x=>x.corpus_id===id)||null; state.catalog=null; state.storage=null; if($('#corpusSelect')&&id)$('#corpusSelect').value=id; if(id){const [catalog,storage]=await Promise.all([api(`/api/corpora/${encodeURIComponent(id)}/catalog`).catch(()=>null),api(`/api/corpora/${encodeURIComponent(id)}/storage`).catch(()=>null)]);state.catalog=catalog;state.storage=storage;} const root=$('#corpusStats'); if(root){const vals=state.selected?[state.selected.assets.length,fmt.format(state.selected.required_blocks),pct(state.selected.semantic_coverage??1),fmt.format(state.selected.unresolved_units||0),state.catalog?.backend||'legacy scan',fmt.format(state.catalog?.indexed_blocks||0),state.storage?.backend||state.storage?.configured_backend||'—',fmt.format(state.storage?.stored_blocks||0)]:['—','—','—','—','—','—','—','—']; [...root.querySelectorAll('strong')].forEach((el,i)=>el.textContent=vals[i]??'—');} const ingest=state.selected?.ingest_coverage??0, semantic=state.selected?.semantic_coverage??0; if($('#ingestCoverageValue'))$('#ingestCoverageValue').textContent=state.selected?pct(ingest):'—'; if($('#semanticCoverageValue'))$('#semanticCoverageValue').textContent=state.selected?pct(semantic):'—'; if($('#ingestCoverageBar'))$('#ingestCoverageBar').style.width=state.selected?pct(ingest):'0%'; if($('#semanticCoverageBar'))$('#semanticCoverageBar').style.width=state.selected?pct(semantic):'0%'; if($('#corpusCoverageNote'))$('#corpusCoverageNote').textContent=state.selected?(state.selected.coverage_ready?`Ingest + semantic ready. ${state.storage?.backend||'payload store'} serves ${fmt.format(state.storage?.stored_blocks||0)} blocks; ${state.catalog?.backend||'catalog'} ranks scheduling only. Execution coverage still gates the score.`:`Corpus is not score-ready: ${state.selected.unresolved_units||0} unresolved semantic unit(s).`):'Final score unlocks only when ingest, semantic, and execution coverage are all complete.'; if(id){await loadStructure(id); await browseBlocks(); await refreshPreflight();} }
async function loadStructure(id){
  const rail=$('#structureRail'); if(!rail)return; try{const d=await api(`/api/corpora/${encodeURIComponent(id)}/structure`); const groups=d.groups||[]; rail.innerHTML=groups.length?groups.map((g,i)=>`<button class="structure-card" data-group-index="${i}"><span>${escapeHtml(g.kind)}</span><strong>${escapeHtml(g.label)}</strong><small>${escapeHtml(g.asset_path.split(/[\\/]/).pop())} · ${fmt.format(g.required_blocks)} blocks</small></button>`).join(''):'<div class="empty-state">No addressable groups found.</div>'; $$('[data-group-index]').forEach(b=>b.addEventListener('click',()=>openStructureGroup(groups[Number(b.dataset.groupIndex)],b)));}catch(e){rail.innerHTML=`<div class="empty-state">${escapeHtml(e.message)}</div>`;}
}
async function openStructureGroup(group,button){ $$('.structure-card').forEach(x=>x.classList.toggle('active',x===button)); const id=$('#corpusSelect').value; const blocks=[]; for(const bid of group.block_ids.slice(0,100)){ try{blocks.push(await api(`/corpora/${encodeURIComponent(id)}/blocks/${encodeURIComponent(bid)}`));}catch{} } renderBlocks(blocks); }
function blockTitle(b){return b.title||(b.text||'').split(/\n/)[0].slice(0,72)||b.id;} function locatorText(b){try{return JSON.stringify(b.source?.locator||{})}catch{return ''}}
function renderBlocks(blocks=[]){ const root=$('#blockList'),count=$('#explorerCount'); if(!root)return; count.textContent=`${fmt.format(blocks.length)} block${blocks.length===1?'':'s'}`; root.innerHTML=blocks.length?blocks.map(b=>`<button class="block-row" data-block-id="${escapeHtml(b.id)}"><span class="block-kind">${escapeHtml(b.modality||b.kind||'block')}</span><span class="block-main"><strong>${escapeHtml(blockTitle(b))}</strong><small>${escapeHtml((b.source?.path||'').split(/[\\/]/).pop())} · ${escapeHtml(locatorText(b))}</small></span><span class="block-size">${fmt.format((b.text||'').length)}c</span></button>`).join(''):'<div class="empty-state">No blocks found.</div>'; $$('[data-block-id]').forEach(el=>el.addEventListener('click',()=>openBlock(el.dataset.blockId,el))); }
async function browseBlocks(){ const id=$('#corpusSelect')?.value;if(!id)return; try{const d=await api(`/api/corpora/${encodeURIComponent(id)}/blocks?limit=100&processable_only=true`);renderBlocks(d.blocks||[])}catch(e){toast(e.message,true)} }
async function searchBlocks(){ const id=$('#corpusSelect')?.value,q=$('#contextSearch')?.value.trim();if(!id)return toast('Choose a corpus first',true);if(!q)return browseBlocks();try{const d=await api(`/api/corpora/${encodeURIComponent(id)}/search?q=${encodeURIComponent(q)}&limit=100`);state.catalog=d.catalog||state.catalog;renderBlocks(d.blocks||[]);toast(`${d.catalog?.backend||'lexical'} ranked ${d.blocks?.length||0} hits · scheduling only`)}catch(e){toast(e.message,true)} }
async function openBlock(blockId,row){const id=$('#corpusSelect')?.value;if(!id)return;try{const b=await api(`/corpora/${encodeURIComponent(id)}/blocks/${encodeURIComponent(blockId)}`);$$('.block-row').forEach(x=>x.classList.toggle('active',x===row));const src=b.source||{};$('#blockDetail').innerHTML=`<p class="eyebrow">Context block</p><h2 style="margin:0 0 12px">${escapeHtml(blockTitle(b))}</h2><div class="detail-grid"><div class="detail-kv"><span>ID</span><code>${escapeHtml(b.id)}</code></div><div class="detail-kv"><span>Modality</span><strong>${escapeHtml(b.modality||'—')} · ${escapeHtml(b.kind||'—')}</strong></div><div class="detail-kv"><span>Parent</span><code>${escapeHtml(b.parent_id||'root')}</code></div><div class="detail-kv"><span>Coverage unit</span><strong>${b.processable?'yes':'structural only'}</strong></div><div class="detail-kv"><span>Semantic status</span><strong>${escapeHtml(b.semantic_status||'ready')}</strong></div><div class="detail-kv"><span>Capabilities</span><strong>${escapeHtml((b.required_capabilities||[]).join(', ')||'text')}</strong></div></div><p class="source-line">${escapeHtml(src.path||'')} · ${escapeHtml(JSON.stringify(src.locator||{}))}</p><pre class="block-text">${escapeHtml(b.text||'[no textual representation]')}</pre>`;}catch(e){toast(e.message,true)}}
function initExplorer(){if(!$('#contextSearchBtn'))return;$('#contextSearchBtn').addEventListener('click',searchBlocks);$('#contextBrowseBtn').addEventListener('click',browseBlocks);$('#contextSearch').addEventListener('keydown',e=>{if(e.key==='Enter')searchBlocks()});}

// ---- Routes -----------------------------------------------------------------
async function loadRoutes(){const d=await api('/api/admin/model-routes');state.routes=d.routes||[];const sel=$('#routeSelect');if(sel){const prev=sel.value;sel.innerHTML='<option value="">Demo judge (offline)</option>'+state.routes.filter(r=>r.enabled).map(r=>`<option value="${escapeHtml(r.id)}">${escapeHtml(r.label)} · ${escapeHtml(r.provider||'generic')} · ${escapeHtml(r.model)}</option>`).join('');if(state.routes.some(r=>r.id===prev))sel.value=prev;}return state.routes;}
async function loadProviders(){try{const d=await api('/api/admin/provider-catalog');state.providers=d.providers||[];const sel=$('#routeProvider');if(sel){sel.innerHTML=state.providers.map(p=>`<option value="${escapeHtml(p.id)}">${escapeHtml(p.label)}</option>`).join('');applyProviderPreset();}}catch(e){state.providers=[];}}
function applyProviderPreset(){const sel=$('#routeProvider');if(!sel)return;const p=state.providers.find(x=>x.id===sel.value);if(!p)return;const base=$('#routeBaseUrl'),caps=$('#routeCapabilities'),hint=$('#providerHint');if(base&&!base.value)base.value=p.default_base_url||'';if(caps&&!caps.value)caps.value=(p.capabilities||[]).join(',');if(hint)hint.innerHTML=`<strong>${escapeHtml(p.label)}</strong><span>${escapeHtml(p.protocol||'adapter')} · ${(p.capabilities||[]).join(' / ')||'text'}${p.native_video?' · native video':''}${p.lmcache?' · LMCache-friendly':''}</span>`;}
async function refreshPreflight(){const corpus=$('#corpusSelect')?.value;if(!corpus||!$('#routePreflightStatus'))return;const route=$('#routeSelect')?.value||null;$('#routePreflightStatus').textContent='Checking…';try{const r=await api('/api/preflight',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({corpus_id:corpus,route_id:route})});$('#routePreflightStatus').textContent=r.ready?'READY':'BLOCKED';$('#routePreflightStatus').className=r.ready?'good':'bad';const need=(r.required_capabilities||[]).join(', ')||'text/table';const missing=(r.unsupported_capabilities||[]).join(', ');$('#routePreflightDetail').textContent=r.ready?`Route can inspect all required blocks. Corpus needs: ${need}.`:`${r.unsupported_blocks||0} block(s) unsupported${missing?` · missing: ${missing}`:''}. Ingest semantic readiness: ${pct(r.semantic_coverage??0)}.`;}catch(e){$('#routePreflightStatus').textContent='ERROR';$('#routePreflightDetail').textContent=e.message;}}

// ---- Evaluation -------------------------------------------------------------
function evalPayload(){ const corpus=$('#corpusSelect')?.value,question=$('#questionInput')?.value.trim(),answer=$('#answerInput')?.value.trim();if(!corpus)throw new Error('Choose a corpus');if(!question)throw new Error('Enter a question');if(!answer)throw new Error('Enter a candidate answer');return {corpus_id:corpus,question,answer,route_id:$('#routeSelect')?.value||null,max_workers:Number($('#workerCount')?.value||4),reduction_batch_size:Number($('#reductionBatch')?.value||32),retry_attempts:2}; }
function renderLiveProgress(d){ if(!$('#resultSection'))return;$('#resultSection').classList.remove('hidden');const cov=Number(d.coverage||0);$('#coverageValue').textContent=pct(cov);$('#coveragePercent').textContent=pct(cov);$('#coverageBar').style.width=pct(cov);$('#visitedValue').textContent=`${fmt.format(d.visited||0)}/${fmt.format(d.total||0)}`;$('#evidenceValue').textContent=fmt.format(d.evidence||0);$('#jobTokenValue').textContent=fmt.format(d.usage?.prompt_tokens||0);const st=$('#resultStatus');st.textContent=d.status||'running';st.className='status '+(d.status==='complete'?'ok':d.status==='failed'||d.status==='blocked'||d.status==='ingest_blocked'||d.status==='capability_blocked'?'fail':'pending');$('#jobLiveDetail').textContent=`${d.status||'running'} · ${d.failed_blocks||0} failed block(s)`;}
function renderFinalJob(j){renderLiveProgress({coverage:j.coverage,visited:j.visited,total:j.total,evidence:(j.evidence||[]).length,status:j.status,failed_blocks:Object.keys(j.failures||{}).length,usage:j.usage});$('#scoreValue').textContent=j.score==null?'—':Number(j.score).toFixed(1).replace('.0','');$('#rationaleText').textContent=j.rationale||'No final score until coverage is complete.';const ev=j.evidence||[];$('#evidenceCount').textContent=`${ev.length} blocks · ${j.evidence_atoms||0} atoms`;const kinds=j.evidence_kind_counts||{};if($('#evidenceTypeSummary'))$('#evidenceTypeSummary').innerHTML=Object.keys(kinds).length?Object.entries(kinds).map(([k,v])=>`<span class="atom-chip" data-kind="${escapeHtml(k)}"><b>${escapeHtml(k)}</b>${fmt.format(v)}</span>`).join(''):'<span class="atom-chip">no typed atoms</span>';$('#evidenceList').innerHTML=ev.length?ev.map(x=>{const atoms=(x.atoms||[]).slice(0,10).map(a=>`<div class="evidence-atom"><strong>${escapeHtml(a.kind||'claim')}</strong>${escapeHtml(a.text||'')}${a.normalized_value?` · ${escapeHtml(a.normalized_value)}${a.unit?escapeHtml(a.unit):''}`:''}</div>`).join('');return `<article class="evidence-item"><div class="evidence-meta"><span>${shortId(x.block_id)} · ${x.modality||'text'}</span><span>${escapeHtml(JSON.stringify(x.source?.locator||{}))}</span></div><p>${escapeHtml(x.note||'')}</p>${atoms?`<div class="evidence-atoms">${atoms}</div>`:''}</article>`}).join(''):'<div class="empty-state">No evidence marked relevant.</div>';}
async function submitEvaluation(){const btn=$('#evaluateBtn'),cancel=$('#cancelEvalBtn');try{const p=evalPayload();btn.disabled=true;btn.textContent='Submitting…';const r=await api('/api/evaluation-jobs',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(p)});state.lastJob=r.job_id;state.lastCorpus=r.corpus_id;if(cancel)cancel.classList.remove('hidden');renderLiveProgress({status:'queued',coverage:0,visited:0,total:state.selected?.required_blocks||0,evidence:0});btn.textContent='Running in background…';await watchEvaluation(r.corpus_id,r.job_id);}catch(e){toast(e.message,true)}finally{btn.disabled=false;btn.textContent='Submit full-coverage job'}}
async function watchEvaluation(corpusId,jobId){for(let i=0;i<7200;i++){try{const j=await api(`/api/jobs/${encodeURIComponent(corpusId)}/${encodeURIComponent(jobId)}`);renderFinalJob(j);if(j.status==='complete'){toast('Full-coverage evaluation complete');return;}if(j.status==='failed'||j.status==='blocked'||j.status==='ingest_blocked'||j.status==='capability_blocked'||j.status==='cancelled'){toast(j.rationale||'Evaluation needs attention',j.status!=='cancelled');return;}}catch(e){if(i>5)throw e;}await new Promise(r=>setTimeout(r,750));}}
async function runBenchmark(){const btn=$('#benchmarkBtn');try{const p=evalPayload();p.tolerance=1;btn.disabled=true;btn.textContent='Benchmarking…';const r=await api('/benchmark',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(p)});const root=$('#benchmarkResult');root.className='benchmark-result';root.innerHTML=`<div class="bench-metric"><span>Direct</span><strong>${r.direct_score.toFixed(2)}</strong></div><div class="bench-metric"><span>Progressive</span><strong>${r.progressive_score.toFixed(2)}</strong></div><div class="bench-metric ${r.passed?'good':'bad'}"><span>Absolute drift</span><strong>${r.absolute_drift.toFixed(3)}</strong></div><div class="bench-metric"><span>Tolerance</span><strong>${r.tolerance.toFixed(2)}</strong></div><div class="bench-metric ${r.passed?'good':'bad'}"><span>Gate</span><strong>${r.passed?'PASS':'FAIL'}</strong></div>`;}catch(e){toast(e.message,true)}finally{btn.disabled=false;btn.textContent='Compare direct vs progressive'}}

// ---- Admin ------------------------------------------------------------------
async function loadAdmin(){try{const d=await api('/api/admin/overview');renderAdmin(d);}catch(e){toast(e.message,true)}}
function renderAdmin(d){
  const metrics=$('#adminMetrics'); if(!metrics)return; const vals=[fmt.format(d.metrics.corpora),fmt.format(d.metrics.ingest_jobs),fmt.format(d.metrics.jobs),fmt.format(d.metrics.indexed_blocks||0),fmt.format(d.metrics.stored_blocks||0),fmt.format(d.metrics.prompt_tokens),money(d.metrics.estimated_cost_usd),fmt.format(d.metrics.pending_failures)];[...metrics.querySelectorAll('strong')].forEach((el,i)=>el.textContent=vals[i]);
  const t=d.telemetry||{};$('#telemetrySource').textContent=t.source||'unconfigured';const tm=$('#telemetryMetrics').querySelectorAll('strong');const tv=[t.lmcache_hit_rate==null?'—':pct(t.lmcache_hit_rate),t.vllm_prefix_hit_rate==null?'—':pct(t.vllm_prefix_hit_rate),t.kv_cache_usage==null?'—':pct(t.kv_cache_usage),t.avg_ttft_seconds==null?'—':`${Number(t.avg_ttft_seconds).toFixed(3)}s`];tm.forEach((el,i)=>el.textContent=tv[i]);$('#telemetryError').textContent=t.error||(!t.raw_metrics_available?'Set CONTEXTMESH_VLLM_METRICS_URL / CONTEXTMESH_LMCACHE_METRICS_URL to connect live metrics.':'');
  const q=d.queue||{stats:{},workers:[],jobs:[]};const qs=q.stats||{};const qm=$('#queueMetrics')?.querySelectorAll('strong')||[];const qv=[qs.queued||0,qs.running||0,qs.failed||0,qs.complete||0];qm.forEach((el,i)=>el.textContent=fmt.format(qv[i]||0));if($('#workersCount'))$('#workersCount').textContent=`${(q.workers||[]).length} workers`;if($('#workerSummary'))$('#workerSummary').textContent=(q.workers||[]).length?(q.workers||[]).map(w=>`${w.worker_id} · ${w.active_job_id?'busy '+shortId(w.active_job_id):'idle'}`).join(' · '):'No active workers. Start `contextmesh worker` or enable the embedded development worker.';if($('#queueJobsTable'))$('#queueJobsTable').innerHTML=(q.jobs||[]).length?(q.jobs||[]).slice(0,50).map(j=>`<tr><td class="mono">${shortId(j.id)}</td><td>${escapeHtml(j.kind)}</td><td class="mono">${shortId(j.logical_job_id)}</td><td><span class="status ${j.status==='complete'?'ok':j.status==='failed'?'fail':'pending'}">${escapeHtml(j.status)}</span></td><td>${j.attempts}/${j.max_attempts}</td><td class="mono">${escapeHtml(j.leased_by||'—')}</td><td class="${j.last_error?'danger-text':''}">${escapeHtml(j.last_error||'—')}</td></tr>`).join(''):'<tr><td colspan="7">No durable queue items yet.</td></tr>';
  const ij=d.ingest_jobs||[];$('#ingestJobsCount').textContent=ij.length;$('#ingestJobsTable').innerHTML=ij.length?ij.map(j=>`<tr><td class="mono">${shortId(j.job_id)}</td><td class="mono">${shortId(j.corpus_id)}</td><td>${pct(j.progress)}</td><td>${j.completed_files}/${j.total_files}</td><td>${bytes(j.total_bytes)}</td><td><span class="status ${j.status==='complete'?'ok':j.status==='failed'?'fail':'pending'}">${j.status}</span></td><td>${escapeHtml(j.message||'')}</td><td>${j.status==='failed'||j.status==='partial'||j.status==='interrupted'?`<button class="tiny-btn" data-retry-ingest="${escapeHtml(j.job_id)}">Retry</button>`:'—'}</td></tr>`).join(''):'<tr><td colspan="8">No ingest jobs.</td></tr>';
  $('#corpusInventoryCount').textContent=d.corpora.length;$('#corporaTable').innerHTML=d.corpora.length?d.corpora.map(c=>`<tr><td class="mono">${shortId(c.corpus_id)}</td><td>${c.assets.length}</td><td>${fmt.format(c.required_blocks)}</td><td>${pct(c.ingest_coverage??1)}</td><td class="${c.semantic_coverage<1?'danger-text':''}">${pct(c.semantic_coverage??1)}</td><td class="${c.unresolved_units?'danger-text':''}">${fmt.format(c.unresolved_units||0)}</td><td>${bytes(c.total_bytes)}</td><td>${Object.entries(c.modality_counts||{}).map(([k,v])=>`${k}:${v}`).join(' · ')||'—'}</td><td class="${c.ingest_warnings?.length?'danger-text':''}">${c.ingest_warnings?.length||0}</td><td><div class="row-actions"><a class="tiny-btn" href="/?corpus=${encodeURIComponent(c.corpus_id)}">Open</a><button class="tiny-btn danger" data-delete-corpus="${c.corpus_id}">Delete</button></div></td></tr>`).join(''):'<tr><td colspan="10">No corpora.</td></tr>';
  $('#jobsCount').textContent=d.jobs.length;$('#jobsTable').innerHTML=d.jobs.length?d.jobs.map(j=>`<tr><td class="mono">${shortId(j.job_id)}</td><td class="mono">${shortId(j.corpus_id)}</td><td>${pct(j.coverage)}</td><td>${j.score==null?'—':Number(j.score).toFixed(1)}</td><td>${fmt.format(j.usage?.prompt_tokens||0)}</td><td>${money(j.usage?.estimated_cost_usd||0)}</td><td class="${j.failures?'danger-text':''}">${j.failures}</td><td><span class="status ${j.status==='complete'?'ok':j.status==='failed'||j.status==='blocked'||j.status==='ingest_blocked'||j.status==='capability_blocked'?'fail':'pending'}">${j.status}</span></td><td>${escapeHtml((j.question||'').slice(0,90))}</td><td><div class="row-actions">${j.status!=='complete'?`<button class="tiny-btn" data-resume-job="${escapeHtml(j.job_id)}" data-corpus="${escapeHtml(j.corpus_id)}">Resume</button>`:''}${['running','queued'].includes(j.status)?`<button class="tiny-btn danger" data-cancel-job="${escapeHtml(j.job_id)}" data-corpus="${escapeHtml(j.corpus_id)}">Cancel</button>`:''}</div></td></tr>`).join(''):'<tr><td colspan="10">No jobs.</td></tr>';
  const failures=d.failures||[];$('#failuresCount').textContent=failures.length;$('#failuresList').innerHTML=failures.length?failures.map(f=>`<div class="failure-item"><code>${shortId(f.block_id)}</code><span>${escapeHtml(f.error)}</span><span class="mono">${shortId(f.job_id)}</span></div>`).join(''):'<div class="empty-state">No failed blocks.</div>';
  $('#runtimeDetails').innerHTML=Object.entries(d.runtime).map(([k,v])=>`<div class="kv-row"><span>${escapeHtml(k)}</span><strong>${escapeHtml(String(v))}</strong></div>`).join('');
  state.routes=d.routes||[];renderRouteList();$$('[data-retry-ingest]').forEach(b=>b.addEventListener('click',async()=>{try{await api(`/api/ingest-jobs/${encodeURIComponent(b.dataset.retryIngest)}/retry`,{method:'POST'});toast('Ingest retry queued');loadAdmin()}catch(e){toast(e.message,true)}}));$$('[data-resume-job]').forEach(b=>b.addEventListener('click',async()=>{try{await api(`/api/evaluation-jobs/${encodeURIComponent(b.dataset.corpus)}/${encodeURIComponent(b.dataset.resumeJob)}/resume`,{method:'POST'});toast('Evaluation resume queued');loadAdmin()}catch(e){toast(e.message,true)}}));$$('[data-cancel-job]').forEach(b=>b.addEventListener('click',async()=>{try{await api(`/api/evaluation-jobs/${encodeURIComponent(b.dataset.corpus)}/${encodeURIComponent(b.dataset.cancelJob)}/cancel`,{method:'POST'});toast('Cancellation requested');loadAdmin()}catch(e){toast(e.message,true)}}));$$('[data-delete-corpus]').forEach(b=>b.addEventListener('click',async()=>{const id=b.dataset.deleteCorpus;if(!confirm(`Delete ${id} and all checkpoints?`))return;try{await api(`/api/corpora/${id}`,{method:'DELETE'});toast('Corpus deleted');loadAdmin()}catch(e){toast(e.message,true)}}));
}
function renderRouteList(){const root=$('#routeList');if(!root)return;$('#routesCount').textContent=state.routes.length;root.innerHTML=state.routes.length?state.routes.map(r=>`<div class="route-item provider-card"><div><div class="route-title-line"><strong>${escapeHtml(r.label)}</strong><span class="provider-badge">${escapeHtml(r.provider||'generic')}</span></div><span>${escapeHtml(r.model)}</span><small>${escapeHtml(r.base_url)} · ${r.max_context_tokens?fmt.format(r.max_context_tokens)+' ctx':'ctx n/a'} · ${(r.capabilities||[]).join(',')||'text'} · max ${r.max_parallel_requests||4} parallel</small></div><div class="row-actions"><button class="tiny-btn" data-test-route="${escapeHtml(r.id)}">Test</button><button class="tiny-btn danger" data-delete-route="${escapeHtml(r.id)}">Delete</button></div></div>`).join(''):'<div class="empty-state">No routes configured. Add a provider route to run live fidelity and evaluation.</div>';$$('[data-delete-route]').forEach(b=>b.addEventListener('click',async()=>{try{await api(`/api/admin/model-routes/${encodeURIComponent(b.dataset.deleteRoute)}`,{method:'DELETE'});toast('Route deleted');loadAdmin()}catch(e){toast(e.message,true)}}));$$('[data-test-route]').forEach(b=>b.addEventListener('click',async()=>{const old=b.textContent;b.disabled=true;b.textContent='Testing…';try{const r=await api(`/api/admin/model-routes/${encodeURIComponent(b.dataset.testRoute)}/test`,{method:'POST'});toast(`Route OK · ${Number(r.latency_seconds||0).toFixed(2)}s`)}catch(e){toast(e.message,true)}finally{b.disabled=false;b.textContent=old}}));}
function initRouteForm(){const btn=$('#saveRouteBtn');if(!btn)return;$('#routeProvider')?.addEventListener('change',()=>{const base=$('#routeBaseUrl'),caps=$('#routeCapabilities');if(base)base.value='';if(caps)caps.value='';applyProviderPreset();});btn.addEventListener('click',async()=>{const id=$('#routeId').value.trim();if(!id)return toast('Route ID required',true);const provider=$('#routeProvider')?.value||'openai-compatible';const p=state.providers.find(x=>x.id===provider);const route={id,label:$('#routeLabel').value.trim()||id,provider,base_url:$('#routeBaseUrl').value.trim()||(p?.default_base_url||''),model:$('#routeModel').value.trim(),api_key_env:$('#routeApiEnv').value.trim()||null,enabled:true,max_context_tokens:Number($('#routeContext').value)||null,input_cost_per_million:Number($('#routeInputCost').value)||0,output_cost_per_million:Number($('#routeOutputCost').value)||0,notes:'',capabilities:($('#routeCapabilities').value||(p?.capabilities||['text','table']).join(',')).split(',').map(x=>x.trim()).filter(Boolean),max_parallel_requests:Number($('#routeParallel').value)||4,request_timeout_seconds:Number($('#routeTimeout').value)||120,deployment:['vllm','sglang'].includes(provider)?'local':'cloud',prompt_cache:provider==='vllm'||provider==='openai'||provider==='gemini',native_file_handles:provider==='gemini'||provider==='openai'};if(!route.base_url||!route.model)return toast('Endpoint and model required',true);try{await api(`/api/admin/model-routes/${encodeURIComponent(id)}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(route)});toast('Model route saved');loadAdmin()}catch(e){toast(e.message,true)}});}

async function init(){await checkHealth();connectEvents();if(document.body.dataset.page==='workspace'){initUpload();initExplorer();$('#refreshCorpora').addEventListener('click',loadCorpora);$('#corpusSelect').addEventListener('change',e=>selectCorpus(e.target.value));$('#routeSelect').addEventListener('change',refreshPreflight);$('#evaluateBtn').addEventListener('click',submitEvaluation);$('#cancelEvalBtn')?.addEventListener('click',async()=>{if(!state.lastJob||!state.lastCorpus)return;try{await api(`/api/evaluation-jobs/${encodeURIComponent(state.lastCorpus)}/${encodeURIComponent(state.lastJob)}/cancel`,{method:'POST'});toast('Cancellation requested');}catch(e){toast(e.message,true)}});$('#benchmarkBtn').addEventListener('click',runBenchmark);await Promise.all([loadCorpora(),loadRoutes()]);const q=new URLSearchParams(location.search).get('corpus');if(q&&state.corpora.some(c=>c.corpus_id===q)){await selectCorpus(q);}else if($('#corpusSelect').value){await selectCorpus($('#corpusSelect').value);}}else{initRouteForm();$('#adminRefresh').addEventListener('click',loadAdmin);await loadProviders();await loadAdmin();}}
init();
